@extends('layouts.public')
@section('title', 'Tareas, notas y diagramas para equipos de trabajo')
@section('content')
<main class="main">
  <section class="hero"><div><span class="eyebrow">TRABAJO CLARO, DE PRINCIPIO A ENTREGA</span><h1>Menos cosas<br>en la cabeza.<br><em>Más claridad.</em></h1><p class="lead">Nexo reúne requerimientos, tareas, listas, archivos y diagramas para que un equipo sepa qué está haciendo, qué falta y qué cambió.</p><div class="actions"><a class="button" href="/app/">Entrar a Nexo →</a>@if(config('nexo.contact_email'))<a class="button secondary" href="mailto:{{ config('nexo.contact_email') }}?subject={{ rawurlencode('Quiero conocer Nexo') }}">Consultar por un piloto</a>@endif</div></div><div class="art" aria-label="Ilustración de Nexo"><span class="orbit"></span><span class="orbit two"></span><span class="tile one">✓</span><span class="tile two">▤</span><span class="tile three">▱</span><span class="center">N</span></div></section>
  <section class="section" id="funciones"><span class="eyebrow">UN SOLO ESPACIO DE TRABAJO</span><h2>De la idea al seguimiento.</h2><p class="section-intro">Cada tarjeta conserva el contexto que el equipo necesita compartir para avanzar.</p><div class="grid"><article class="feature"><span class="feature-icon">▥</span><h3>Tablero por ambiente</h3><p>Organiza tareas desde el trabajo inicial hasta QA, certificación y producción, con sus estados y motivos de regreso.</p></article><article class="feature"><span class="feature-icon">☑</span><h3>Notas y listas útiles</h3><p>Escribe ideas o convierte una nota en una lista interactiva para marcar lo que ya hiciste.</p></article><article class="feature"><span class="feature-icon">◇</span><h3>Diagramas y archivos</h3><p>Explica un proceso con una pizarra y guarda documentos, imágenes y otros recursos junto al trabajo.</p></article><article class="feature"><span class="feature-icon">✉</span><h3>Avisos por correo</h3><p>Elige destinatarios y qué información incluir en los avisos de entrega configurados para las tareas.</p></article><article class="feature"><span class="feature-icon">♙</span><h3>Acceso por persona</h3><p>La administración asigna los espacios y define quién puede editar o consultar.</p></article><article class="feature"><span class="feature-icon">⌁</span><h3>Web y Android</h3><p>La aplicación Android acompaña la misma cuenta y el mismo servidor que la versión web.</p></article></div></section>
  <section class="section"><span class="eyebrow">CÓMO EMPEZAR</span><h2>Primero con tu equipo.</h2><div class="steps"><article class="step"><b>1</b><p>La persona administradora crea el espacio y agrega a quienes participarán.</p></article><article class="step"><b>2</b><p>El equipo registra solicitudes, agrega checklist y mantiene las decisiones a mano.</p></article><article class="step"><b>3</b><p>Las tarjetas avanzan por ambientes; el historial deja claro por qué una volvió atrás.</p></article></div></section>
  <section class="section"><div class="scope"><strong>Un alcance claro para empezar.</strong> Nexo organiza y documenta el seguimiento. No despliega software ni sustituye las herramientas de desarrollo. Hoy se ofrece como piloto guiado, con una instalación independiente por equipo; el acceso se habilita por invitación.</div></section>
</main>
@endsection
