@extends('layouts.public')
@section('title', 'Privacidad')
@section('content')
<main class="main doc"><span class="eyebrow">INFORMACIÓN DEL SERVICIO</span><h1>Privacidad</h1><p>Última revisión: 26 de septiembre de 2026.</p><div class="notice"><strong>Documento de lanzamiento pendiente de validación.</strong> Antes de usar Nexo con datos de clientes, la persona operadora debe completar la identidad legal, domicilio, proveedores y plazos de conservación de esta instalación, y revisar el texto con asesoría local. No representa una certificación de cumplimiento.</div>
<h2>Quién opera esta instalación</h2><p>Responsable u operador: <strong>{{ config('nexo.legal_name') ?: 'identidad legal aún no configurada' }}</strong>. Domicilio: <strong>{{ config('nexo.legal_address') ?: 'domicilio aún no configurado' }}</strong>. Correo de privacidad: @if(config('nexo.privacy_email'))<a href="mailto:{{ config('nexo.privacy_email') }}">{{ config('nexo.privacy_email') }}</a>@else<strong>correo aún no configurado</strong>@endif.</p>
<h2>Qué información guarda Nexo</h2><p>La instalación puede guardar nombres y correos de las cuentas, contraseñas protegidas mediante hash, datos de autenticación, tareas, descripciones, checklists, notas, diagramas, archivos adjuntos, preferencias y actividad del espacio. La persona administradora y las personas autorizadas pueden introducir datos de otras personas; deben contar con la base y los permisos necesarios para hacerlo.</p>
<h2>Para qué se usa</h2><p>La información se utiliza para iniciar sesión, mostrar y compartir el contenido entre integrantes autorizados, registrar cambios y enviar los avisos por correo que la persona usuaria configure. No uses Nexo para claves, datos bancarios ni información especialmente sensible.</p>
<h2>Servicios que intervienen</h2><p>El alojamiento, la base de datos y el correo dependen de los proveedores configurados por quien administra cada instalación. Completa aquí los nombres, ubicaciones y funciones de los proveedores reales antes de ofrecer el servicio. El correo de aviso puede incluir campos de la tarea que seleccione la persona usuaria.</p>
<h2>Acceso, solicitudes y conservación</h2><p>El administrador de la instalación controla las cuentas. Para consultar, corregir, exportar o solicitar la eliminación de información, contacta a la persona administradora o escribe a la dirección de privacidad configurada. Define y publica plazos de retención, cómo se eliminan los respaldos y qué ocurre al terminar el servicio antes de incorporar datos de clientes.</p>
<h2>Seguridad y cambios</h2><p>Nexo ofrece controles de acceso, permisos por espacio, segundo factor opcional, límites ante intentos fallidos y archivos privados. Ningún servicio conectado a Internet puede prometer seguridad absoluta. Esta página puede actualizarse cuando cambien el servicio o sus proveedores.</p>
</main>
@endsection
