import {Component,Input,Output,EventEmitter,ViewChild,ElementRef,signal,OnDestroy} from '@angular/core';
import {CommonModule} from '@angular/common';
import {FormsModule} from '@angular/forms';
export type FlowNode={id:string;label:string;shape:'process'|'decision'|'terminal';x?:number;y?:number};
export type Diagram={direction:'TD'|'LR';nodes:FlowNode[];edges:{from:string;to:string;label:string}[]};
export function emptyDiagram():Diagram{return {direction:'TD',nodes:[{id:'n1',label:'Inicio',shape:'terminal'},{id:'n2',label:'Procesar solicitud',shape:'process'},{id:'n3',label:'Fin',shape:'terminal'}],edges:[{from:'n1',to:'n2',label:''},{from:'n2',to:'n3',label:''}]};}
@Component({selector:'app-diagram',standalone:true,imports:[CommonModule,FormsModule],template:`
<div class="diagram-toolbar"><span>{{readonly?'Diagrama de flujo':'Conecta pasos y arrástralos para ordenar'}}</span><div><button type="button" class="button secondary" (click)="exportFile('png')" [disabled]="exporting()">Imagen PNG</button><button type="button" class="button secondary" (click)="exportFile('pdf')" [disabled]="exporting()">{{exporting()?'Exportando…':'PDF'}}</button></div></div>
@if(error()){<p class="error" role="alert">{{error()}}</p>}@if(download();as file){<p class="export-ready" role="status">Archivo listo. <a [href]="file.url" [download]="file.name">Descargar {{file.name}}</a></p>}
<div class="flow-canvas" [class.is-editable]="!readonly"><svg #canvas xmlns="http://www.w3.org/2000/svg" [attr.viewBox]="'0 0 '+width+' '+height" [style.min-width.px]="Math.min(width,1200)" [style.height.px]="Math.min(height,850)" role="img" aria-label="Diagrama de flujo" (pointermove)="move($event)" (pointerup)="stop()" (pointercancel)="stop()">
<defs><marker [attr.id]="markerId" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto" markerUnits="strokeWidth"><path d="M0,0 L0,6 L9,3 z" fill="#64748b"/></marker></defs>
@for(edge of diagram.edges;track $index){<g><path [attr.d]="path(edge)" fill="none" stroke="#64748b" stroke-width="2" [attr.marker-end]="'url(#'+markerId+')'"/><text [attr.x]="edgePoint(edge).x" [attr.y]="edgePoint(edge).y-8" text-anchor="middle" font-family="Arial,sans-serif" font-size="12" fill="#334155" stroke="#fff" stroke-width="5" paint-order="stroke">{{edge.label}}</text></g>}
@for(node of diagram.nodes;track node.id){<g [attr.transform]="'translate('+position(node).x+','+position(node).y+')'" (pointerdown)="start($event,node)" [style.cursor]="readonly?'default':'grab'">
@if(node.shape==='decision'){<polygon points="100,0 200,50 100,100 0,50" fill="#fff3cf" stroke="#d49b17" stroke-width="2"/>}@else{<rect width="200" height="100" [attr.rx]="node.shape==='terminal'?50:12" [attr.fill]="node.shape==='terminal'?'#e1f5ed':'#edf1ff'" [attr.stroke]="node.shape==='terminal'?'#39997a':'#6479d9'" stroke-width="2"/>}
<text x="100" [attr.y]="50-(lines(node.label).length-1)*8" text-anchor="middle" font-family="Arial,sans-serif" font-size="13" fill="#17233b">@for(line of lines(node.label);track $index){<tspan x="100" [attr.dy]="$index===0?0:17">{{line}}</tspan>}</text></g>}
</svg></div>
@if(!readonly){<div class="flow-builder"><section><div class="section-header"><h3>Pasos</h3><button type="button" class="text-button" (click)="addNode()" [disabled]="diagram.nodes.length>=60">＋ Agregar paso</button></div><div class="flow-layout"><label>Dirección<select [(ngModel)]="diagram.direction" [ngModelOptions]="{standalone:true}" (ngModelChange)="arrange()"><option value="TD">De arriba hacia abajo</option><option value="LR">De izquierda a derecha</option></select></label><button type="button" class="button secondary" (click)="arrange()">Ordenar pasos</button></div>@for(node of diagram.nodes;track node.id){<div class="flow-node-row"><span>{{ $index+1 }}</span><input aria-label="Nombre del paso" [(ngModel)]="node.label" [ngModelOptions]="{standalone:true}" (ngModelChange)="changed()" maxlength="180"><select aria-label="Tipo de paso" [(ngModel)]="node.shape" [ngModelOptions]="{standalone:true}" (ngModelChange)="changed()"><option value="process">Proceso</option><option value="decision">Decisión</option><option value="terminal">Inicio / fin</option></select><button type="button" class="icon-button danger" (click)="removeNode(node.id)" [disabled]="diagram.nodes.length<=1" aria-label="Eliminar paso">×</button></div>}</section><section><div class="section-header"><h3>Conexiones</h3><button type="button" class="text-button" (click)="addEdge()" [disabled]="diagram.edges.length>=120">＋ Conectar</button></div>@for(edge of diagram.edges;track $index){<div class="flow-edge-row"><select aria-label="Paso de origen" [(ngModel)]="edge.from" [ngModelOptions]="{standalone:true}" (ngModelChange)="changed()">@for(node of diagram.nodes;track node.id){<option [value]="node.id">{{node.label}}</option>}</select><span>→</span><select aria-label="Paso de destino" [(ngModel)]="edge.to" [ngModelOptions]="{standalone:true}" (ngModelChange)="changed()">@for(node of diagram.nodes;track node.id){<option [value]="node.id">{{node.label}}</option>}</select><input aria-label="Etiqueta de conexión" placeholder="Ej. Sí / No" [(ngModel)]="edge.label" [ngModelOptions]="{standalone:true}" (ngModelChange)="changed()" maxlength="80"><button type="button" class="icon-button danger" (click)="diagram.edges.splice($index,1);changed()" aria-label="Eliminar conexión">×</button></div>}</section></div>}
`})
export class DiagramComponent implements OnDestroy {
 @Input() diagram:Diagram=emptyDiagram();@Input() readonly=false;@Input() title='Diagrama';@Output() diagramChange=new EventEmitter<Diagram>();@ViewChild('canvas') canvas!:ElementRef<SVGSVGElement>;
 Math=Math; markerId='arrow-'+Math.random().toString(36).slice(2);error=signal('');exporting=signal(false);download=signal<{url:string;name:string}|null>(null);
 ngOnDestroy(){const file=this.download();if(file)URL.revokeObjectURL(file.url);}
 private dragging:FlowNode|null=null;private dragBounds:{w:number;h:number}|null=null; private offset={x:0,y:0};
 position(n:FlowNode){const i=this.diagram.nodes.indexOf(n);return {x:n.x??(this.diagram.direction==='LR'?40+i*290:80),y:n.y??(this.diagram.direction==='TD'?40+i*180:50)};}
 get width(){return this.dragBounds?.w??Math.max(800,...this.diagram.nodes.map(n=>this.position(n).x+250));}
 get height(){return this.dragBounds?.h??Math.max(650,...this.diagram.nodes.map(n=>this.position(n).y+150));}
 lines(s:string){const words=s.match(/.{1,22}(?:\s|$)|.{1,22}/g)||[''];const result=[''];for(const word of words){if((result[result.length-1]+' '+word).length>23&&result[result.length-1])result.push('');result[result.length-1]+=(result[result.length-1]?' ':'')+word;}return result.slice(0,5);}
 endpoints(e:Diagram['edges'][0]){const a=this.diagram.nodes.find(n=>n.id===e.from),b=this.diagram.nodes.find(n=>n.id===e.to);const p=a?this.position(a):{x:0,y:0},q=b?this.position(b):{x:0,y:0};if(this.diagram.direction==='LR')return {x1:p.x+200,y1:p.y+50,x2:q.x,y2:q.y+50};return {x1:p.x+100,y1:p.y+100,x2:q.x+100,y2:q.y};}
 path(e:Diagram['edges'][0]){const p=this.endpoints(e);if(e.from===e.to)return `M ${p.x1} ${p.y1} C ${p.x1+190} ${p.y1+110},${p.x2+190} ${p.y2-110},${p.x2} ${p.y2}`;return this.diagram.direction==='LR'?`M${p.x1},${p.y1} C${(p.x1+p.x2)/2},${p.y1} ${(p.x1+p.x2)/2},${p.y2} ${p.x2},${p.y2}`:`M${p.x1},${p.y1} C${p.x1},${(p.y1+p.y2)/2} ${p.x2},${(p.y1+p.y2)/2} ${p.x2},${p.y2}`;}
 edgePoint(e:Diagram['edges'][0]){const p=this.endpoints(e);return {x:(p.x1+p.x2)/2,y:(p.y1+p.y2)/2};}
 changed(){this.diagramChange.emit({...this.diagram});}
 addNode(){const max=Math.max(0,...this.diagram.nodes.map(n=>Number(n.id.slice(1))));this.diagram.nodes.push({id:'n'+(max+1),label:'Nuevo paso',shape:'process'});this.changed();}
 removeNode(id:string){this.diagram.nodes=this.diagram.nodes.filter(n=>n.id!==id);this.diagram.edges=this.diagram.edges.filter(e=>e.from!==id&&e.to!==id);this.changed();}
 addEdge(){this.diagram.edges.push({from:this.diagram.nodes[0].id,to:this.diagram.nodes[this.diagram.nodes.length-1].id,label:''});this.changed();}
 arrange(){this.diagram.nodes.forEach(n=>{delete n.x;delete n.y;});this.changed();}
 point(e:PointerEvent){const p=new DOMPoint(e.clientX,e.clientY);return p.matrixTransform(this.canvas.nativeElement.getScreenCTM()!.inverse());}
 start(e:PointerEvent,n:FlowNode){if(this.readonly)return;e.preventDefault();const p=this.point(e),nPos=this.position(n);this.offset={x:p.x-nPos.x,y:p.y-nPos.y};this.dragBounds={w:this.width,h:this.height};this.dragging=n;this.canvas.nativeElement.setPointerCapture(e.pointerId);}
 move(e:PointerEvent){if(!this.dragging)return;const p=this.point(e);this.dragging.x=Math.max(10,Math.min(this.width-210,5000,p.x-this.offset.x));this.dragging.y=Math.max(10,Math.min(this.height-110,5000,p.y-this.offset.y));}
 stop(){if(this.dragging){this.dragging=null;this.dragBounds=null;this.changed();}}
 async exportFile(type:'png'|'pdf'){
  this.exporting.set(true);this.error.set('');const previous=this.download();if(previous)URL.revokeObjectURL(previous.url);this.download.set(null);let url='';try{
   const copy=this.canvas.nativeElement.cloneNode(true) as SVGSVGElement;copy.setAttribute('width',String(this.width));copy.setAttribute('height',String(this.height));copy.removeAttribute('style');
   url=URL.createObjectURL(new Blob([new XMLSerializer().serializeToString(copy)],{type:'image/svg+xml;charset=utf-8'}));const img=new Image();img.src=url;await img.decode();
   const canvas=document.createElement('canvas'),scale=Math.min(2,4000/Math.max(this.width,this.height));canvas.width=Math.ceil(this.width*scale);canvas.height=Math.ceil(this.height*scale);const ctx=canvas.getContext('2d')!;ctx.fillStyle='#ffffff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);const data=canvas.toDataURL('image/png');const name=(this.title.replace(/[^a-zA-Z0-9áéíóúñ _-]/g,'').trim()||'Diagrama').slice(0,100);
   let blob:Blob;
   if(type==='png'){blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('PNG')),'image/png'));}
   else{const {jsPDF}=await import('jspdf');const pdf=new jsPDF({orientation:this.width>this.height?'landscape':'portrait',unit:'mm',format:'a4'});const w=pdf.internal.pageSize.getWidth()-20,h=pdf.internal.pageSize.getHeight()-20,r=Math.min(w/this.width,h/this.height);pdf.addImage(data,'PNG',10,10,this.width*r,this.height*r);blob=pdf.output('blob');}
   const result={url:URL.createObjectURL(blob),name:name+'.'+type};this.download.set(result);const anchor=document.createElement('a');anchor.href=result.url;anchor.download=result.name;document.body.appendChild(anchor);anchor.click();anchor.remove();

  }catch{this.error.set('No se pudo exportar el diagrama. Vuelve a intentarlo.');}finally{if(url)URL.revokeObjectURL(url);this.exporting.set(false);}
 }
}
